<?php
/**
 * Created by Rativardhan Singh Sengar on 9/19/18 9:45 PM
 * Copyright (c) 2018 . All rights reserved.
 * Last modified 9/19/18 9:05 PM
 */

return [

    'scraper_url' => ['base_url' => 'http://18.222.41.99/scraper/scraperjson/'],

    'find_short_address' => [" South ",
                              " North ",
                              " West ",
                              " East ",
                              " northeast",
                              " southeast",
                              " southwest",
                              " northwest",
                              " Court",
                              " Lane",
                              " Street",
                              " Road",
                              " Terrace",
                              " Circle",
                              " Highway",
                              " Parkway",
                              " Avenue",
                              " Ridge",
                              " Boulevard",
                              " Drive",
                              " Center",
                              " Expressway",
                              " Island",
                              " Junction",
                              " Lake",
                              " Mountain",
                              " Place",
                              " Plaza",
                              " Square",
                              " Station",
                              " Turnpike",
                              " Valley",
                              " Way"

    ],

     'replace_detail_address' => [" S ",
                                  " N ",
                                  " W ",
                                  " E ",
                                  " ne",
                                  " se",
                                  " sw",
                                  " nw",
                                  " Ct",
                                  " Ln",
                                  " St",
                                  " Rd",
                                  " Terr",
                                  " Cir",
                                  " Hwy",
                                  " Pkwy",
                                  " Ave",
                                  " Rdg",
                                  " Blvd",
                                  " Dr",
                                  " Ctr",
                                  " Expy",
                                  " Is",
                                  " Jct",
                                  " Lk",
                                  " Mt",
                                  " PL",
                                  " Plz",
                                  " Sq",
                                  " Sta",
                                  " TPKE",
                                  " VLY",
                                  " Wy"

     ],

    'booster_plan'       => ['west_nc' => '6 to 25 counties is $300 a month',
                             'full_nc' => 'Unlimited counties $500 a month',],
    'first_county_price' => 99.97,
    'per_county_price'   => 0,
    'roles_es'           => [//'admin' => 'Admin',
                             //'web_team' => 'Web Team',
                             'chief_dca'       => 'Chief DCA',
                             'am'              => 'Acquisitions Manager',
                             'first_dtc'       => 'First DTC',
                             'second_dca'      => 'Second DCA',
                             'third_dca'       => 'Third DCA',
                             'nos_by'          => 'Nos By',
                             'im_by'           => 'IM By',
                             'trustee_callers' => 'Trustee Callers',
                             'accounting'      => 'Accounting',
                             'sub_to'          => 'Sub To'],
    'roles_buyer'        => ['home_buyer'      => 'Home Buyer',
                             'wholesale_buyer' => 'WholeSale Buyer',
                             'fund_lander'     => 'Fund Lender',],
    "states"             => array('AL' => 'Alabama',
                                  'AK' => 'Alaska',
                                  'AZ' => 'Arizona',
                                  'AR' => 'Arkansas',
                                  'CA' => 'California',
                                  'CO' => 'Colorado',
                                  'CT' => 'Connecticut',
                                  'DE' => 'Delaware',
                                  'DC' => 'District Of Columbia',
                                  'FL' => 'Florida',
                                  'GA' => 'Georgia',
                                  'HI' => 'Hawaii',
                                  'ID' => 'Idaho',
                                  'IL' => 'Illinois',
                                  'IN' => 'In.diana',
                                  'IA' => 'Iowa',
                                  'KS' => 'Kansas',
                                  'KY' => 'Kentucky',
                                  'LA' => 'Louisiana',
                                  'ME' => 'Maine',
                                  'MD' => 'Maryland',
                                  'MA' => 'Massachusetts',
                                  'MI' => 'Michigan',
                                  'MN' => 'Minnesota',
                                  'MS' => 'Mississippi',
                                  'MO' => 'Missouri',
                                  'MT' => 'Montana',
                                  'NE' => 'Nebraska',
                                  'NV' => 'Nevada',
                                  'NH' => 'New Hampshire',
                                  'NJ' => 'New Jersey',
                                  'NM' => 'New Mexico',
                                  'NY' => 'New York',
                                  'NC' => 'North Carolina',
                                  'ND' => 'North Dakota',
                                  'OH' => 'Ohio',
                                  'OK' => 'Oklahoma',
                                  'OR' => 'Oregon',
                                  'PA' => 'Pennsylvania',
                                  'RI' => 'Rhode Island',
                                  'SC' => 'South Carolina',
                                  'SD' => 'South Dakota',
                                  'TN' => 'Tennessee',
                                  'TX' => 'Texas',
                                  'UT' => 'Utah',
                                  'VT' => 'Vermont',
                                  'VA' => 'Virginia',
                                  'WA' => 'Washington',
                                  'WV' => 'West Virginia',
                                  'WI' => 'Wisconsin',
                                  'WY' => 'Wyoming',)

];
