<?php
/**
 * Created by Rativardhan Singh Sengar on 9/19/18 9:45 PM
 * Copyright (c) 2018 . All rights reserved.
 * Last modified 9/19/18 9:05 PM
 */

return [
    'ext_wall_type' => [
        '0'  => 'N/A',
        '1'  => 'Brick',
        '2'  => 'Brick Veneer',
        '3'  => 'Siding',
        '4'  => 'Cement/Wood Fiber Siding',
        '5'  => 'Fiber/Cement Siding',
        '6'  => 'Wood Siding',
        '7'  => 'Vinyl Siding',
        '8'  => 'Aluminum Siding',
        '9'  => 'Alum/Vinyl Siding',
        '10' => 'Brick/Vinyl Siding',
        '11' => 'Wood/Vinyl Siding',
        '12' => 'Brick/Wood Siding',
        '13' => 'Stone',
        '14' => 'Masonry',
        '15' => 'Metal',
        '16' => 'Fiberboard',
        '17' => 'Asphalt Siding',
        '18' => 'Concrete Block',
        '19' => 'Gable',
        '20' => 'Frame'

        ,
    ],
    'roofing'       => [
        '0'  => 'N/A',
        '1'  => 'Asphalt Shingle',
        '2'  => 'Composition Shingle',
        '3'  => 'Composite Shingle Heavy',
        '4'  => 'Solar tiles',
        '5'  => 'Metal',
        '6'  => 'Stone-coated steel',
        '7'  => 'Slate',
        '8'  => 'Rubber Slate',
        '9'  => 'Clay and Concrete tiles',
        '10' => 'Green Roofs',
        '11' => 'Built-up Roofing',
    ],
    'ac_heating'    => [
        '0' => 'N/A',
        '1' => 'Central',
        '2' => 'Heat Pump',
        '3' => 'Warm Air',
        '4' => 'Forced Air',
        '5' => 'Gas',
        '9' => 'N/A',
    ],
    'pool_spa'      => [
        '0' => 'N/A',
        '1' => 'Yes -Pool Only',
        '2' => 'Yes -Spa Only',
        '3' => 'Yes -Both Pool & Spa',
        '9' => 'None',
    ],
    'garage_types'  => [
        '0' => 'N/A',
        '1' => 'Attached',
        '2' => 'Basement',
        '3' => 'Built In',
        '4' => 'Detached',
        '5' => 'Carport',
        '9' => 'N/A',
    ],
    'fireplace'     => [
        '1' => 'Yes',
        '0' => 'No',
    ],

    'property_types'          => [
        '0' => 'N/A',
        '1' => 'Residential',
        '2' => 'Land',
        '3' => 'Commercial',
        '4' => 'Industrial',
        '5' => 'Water'
    ],

    
    
    'specific_property_types' => [
        '1' => ['Residential' => [
            '0' => 'N/A',
            "1" => "Single Family",
            "2" => "Condominium",
            "3" => "Townhouse",
            "4" => "Multi-Family",
            "5" => "Manufactured",
            "6" => "Mobile Home",
            "61"=> "Lake Front",
            "62"=> "Ocean Front",
            "63"=> "Golf Course front"
        ]],
        '2' => ['Land' => [
            '0'  => 'N/A',
            "21" => "Vacant",
            "22" => "Vacant Undeveloped",
            "23" => "Land In Transition or Early Dev't Stage",
            "24" => "Agricultural Use & Ranches",
            "25" => "Subdivision and Lot Wholesaling",
            "26" => "Site Location and Assembling Parcels",
            "27" => "Waterfront",
            "28" => "Waterfront with Boat Slip/Dock",
            "61"=> "Lake Front",
            "62"=> "Ocean Front",
            "63"=> "Golf Course front"
        ]],
        '3' => ['Commercial' => [
            '0'  => 'N/A',
            "31" => "Shopping Center",
            "31" => "Strip Mall",
            "33" => "Medical",
            "34" => "Educational",
            "35" => "Apartment",
            "36" => "Hotel",
            "37" => "Offices",
            "38" => "Vacant Land",
            "39" => "Boat Dock/Slip",
            
        ]],
        '4' => ['Industrial' => [
            '0'  => 'N/A',
            "41" => "Manufacturing",
            "42" => "Manufacturing/Warehouse",
            "43" => "Warehouse",
            "44" => "Distribution",
            "45" => "Refrigeration/Cold Storage",
            "46" => "Telecom/Data Hosting Centers",
            "47" => "Flex Buildings",
            "48" => "R&D Buildings",
            "49" => "Showroom /Retail",
            "61"=> "Lake Front",
            "62"=> "Ocean Front",
            "63"=> "Golf Course front"
        ]],
        '5' => ['Water'=>[
            '0'=>'N/A',
            '51'=>'Boat Slip/Dock'
        ]]
    ],

    'specific_property_location' => [
        '0'  => 'N/A',
        "61"=> "Lake Front",
        "62"=> "Ocean Front",
        "63"=> "Golf Course front",
        "64"=>"Water Front"
    ],

    'pick_from'=>[
        '1'=>'Land 5 Acres or Larger',
        '2'=>'Commercial Property',
        '3'=>'Lots Good Quality',
        '4'=>'House',
        // '5'=>'Excess/Surplus Funds',
        '6'=>'Other'        
    ],

    'building_style' => [
        '0'  => 'N/A',
        '1'  => 'One Story',
        '2'  => 'Two Story',
        '3'  => 'Conventional',
        '4'  => 'Ranch',
        '5'  => 'Ranch with Basement',
        '6'  => 'Cape Cod',
        '7'  => 'Contemporary',
        '8'  => 'Colonial',
        '9'  => 'Mediterranean',
        '10' => 'Craftsman',
        '11' => 'Log/Cabin',
        '12' => 'Split-Level',
        '13' => 'Split-Foyer',
        '14' => 'Stick Built',
        '15' => 'Single wide',
        '16' => 'Double wide',
        '17' => 'Duplex',
        '18' => 'Triplex',
        '19' =>       'Quadruplex',
        '20' => 'Victorian',
        '21' => 'Tudor',
        '22' => 'Modern',
        '23' => 'Art Deco',
        '24' => 'Bungalow',
        '25' => 'Mansion',
        '26' => 'Farmhouse',
    ],

    # Price History : description dropdown
    'ph_description' => [
        '0' => 'N/A',
        '1' => 'Listed',
        '2' => 'Change Price',
        '3' => 'Sold',
        '4' => 'Pending',
        '5' => 'Back on market',
        '6' => 'Public Record',
        '7' => 'For Rent',
        '8' => 'Listing Removed',
        '9' => 'Under Contract'
    ],

    'owner_document_type'    => [
        '4'  => 'Clear (Current Owner)',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Clear (Previous Owner)',
        '8'  => 'Clear (Borrower)',
        '9'  => 'Clear (Related Results)',
        '10'  => 'Pacer (Current Owner)',
        '11'  => 'Pacer (Previous Owner)',
        '12'  => 'Pacer (Borrower)',
        '99' => 'Other',
    ],
    'borrower_document_type' => [
        '1'  => 'Tax Statement',
        '2'  => 'Property Record Card',
        '3'  => 'Clear (Property)',
        '4'  => 'Clear (Owner)',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Trustees Deed',
        '8'  => 'Deed of Trust',
        '9'  => 'Modification',
        '10' => 'Subordination',
        '11' => 'Affidavit',
        '12' => 'Order',
        '99' => 'Other',
    ],
    'property_info_document_type' => [
        '1'  => 'Tax Statement',
        '2'  => 'Property Record Card',
        '3'  => 'Clear (Property)',
        '4'  => 'Clear (Owner)',
        '5'  => 'Plat Map'
    ],
    'property_document_type' => [
        '1'  => 'Tax Statement',
        '2'  => 'Property Record Card',
        '3'  => 'Clear (Property)',
        '4'  => 'Clear (Owner)',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Trustees Deed',
        '8'  => 'Deed of Trust',
        '9'  => 'Modification',
        '10' => 'Subordination',
        '11' => 'Affidavit',
        '12' => 'Order',
        '99' => 'Other',
    ],
    'sale_status'            => [
        '0'  => 'N/A',
        '1'  => 'Active',
        '2'  => 'Postponed',
        '3'  => 'Cancelled',
        '4'  => 'Sale Closed',
        '5'  => 'Sale Date Confirmed',
        '6'  => 'Sale Date Unconfirmed',
        '7'  => 'Property Redeemed',
        '8'  => 'Struck Off',
        '9'  => 'Tax Resale',
        '10' => 'No Sale Date Yet',
        '11' => 'Hearing - No Sale Date Yet',
        '12' => 'Redemption'
    ],

    'doc_type'  => [
        '1'  => 'NOS',
        '2'  => 'RPFS',
        '3'  => 'UPST',
        '4'  => 'FAOF',
        '5'  => 'VCAP NOS',
        '6'  => 'VCAP RPFS',
        '7'  => 'VCAP UPST',
        '8'  => 'Tax Sale RPFS',
        '9'  => 'Tax Sale UPST',
        '10' => 'FRAR',
        '11' => 'Appointment',
        '12' => 'Notice of Hearing',
        '13' => 'Postponement',
        '14' => 'Notice of Cancellation',
    ],
    'sale_doc_type'=>[
      '1'  => 'NOS (VCAP)',
      '2'  => 'NOS (County)',
      '3'  => 'NOS (Newspaper)',
      '4'  => 'Notice of Hearing (VCAP)',
      '5'  => 'Notice of Hearing (County)',
      '6'  => 'Notice of Hearing (Newspaper)',
      '7'  => 'Master in Equity (SC)',
      '8'  => "APPT (TX)",
      '9'  => "Notice of Trustee's Sale (TX)",
      '10' => 'Tax List (Trustee)',
      '11' => 'Tax List (County)',
      '12' => 'Tax List (Newspaper)',
      '13' => 'Mortgage List (Trustee)',
      '14' => 'POSTPONEMENT',
      '15' => 'Other'
    ],

    'sale_type' => [
        '0'  => 'N/A',
        // '1'  => 'Mortgage Foreclosure',
        '2'  => '1st Lien Frcl',
        '3'  => '2nd Lien Frcl',
        '4'  => '3rd Lien Frcl',
        '5'  => 'HOA Sale',
        '6'  => 'Tax Sale',
        '7'  => 'Estate Sale',
        //'8'  => 'Judicial',
        //'9'  => 'Non Judicial',
        '10' => 'Struck Off',
        '11' => 'Surplus',
        //'12' => 'REO',
        //'13' => 'Short Sale',
        '14' => 'Requested Record',
        '15' => 'Appointment',
        //'16' => 'FSBO',
        //'17' => 'REIA',
        '18' => 'Timeshare',
        '19' => 'Wholesale',
        '20' => 'Future Sale',
        '21' => '1st Lien and HOA Sale',
        '22' => '2nd Lien and HOA Sale',
        '23' => '3rd Lien and HOA Sale',
        '24' => 'HOA and Tax Sale',
        '25' => 'Private sale',
        '26'  => '4th Lien Frcl',
        '27' =>'Auction.com',
        //'99' => 'NONE',
    ],

    'right_to_cure' => [
        '5'  => '5',
        '10' => '10',
        '15' => '15',
        '20' => '20',
        '25' => '25',
        '30' => '30',
    ],

    'listing' => [
        '0' => 'N/A',
        '1' => 'MLS',
        '2' => 'CMLS',
        '3' => 'TMLS',
        '4' => 'TRIAD',
        '5' => 'WRAR',
        '6' => 'FLEX',
        '7' => 'PARAGON',
        '8' => 'NAVICA',
    ],

    'document_type' => [
        '1'  => 'Tax Statement',
        '2'  => 'Property Record Card',
        '3'  => 'Clear (Property)',
        '4'  => 'Clear (Owner)',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Trustees Deed',
        '8'  => 'Deed of Trust',
        '9'  => 'Modification',
        '10' => 'Subordination',
        '11' => 'Affidavit',
        '12' => 'Order',
        '99' => 'Other',
    ],

    'loan_type' => [
        '0'  => 'N/A',
        '1'  => 'CONVENTIONAL',
        '2'  => 'PURCHASE MONEY',
        '3'  => 'FHA',
        '4'  => 'VA/RHS',
        '5'  => 'USDA',
        '6'  => 'FNMA/FHLMC',
        '7'  => 'ARM',
        '8'  => 'HOME EQUITY',
        '9'  => 'HELOC',
        '10' => 'HUD',
        '11' => 'ARM',
        '12' => 'FIXED RATE',
        '13' => 'SECOND LIEN',
        '14' => 'INFERIOR LIEN',
        '15' => 'PRIVATE',
        '16' => 'REVERSE',
        '17' => 'OPEN-END',
        '18' => 'CLOSE-END',
        '19' => 'DPAL',
    ],

    'picture_type'  => [
        '1' => 'All',
        '2' => 'Before Pictures',
        '3' => 'After Pictures',
        '4' => 'Highlight Pictures',
        '5' => 'Pulled Pictures',
        '6' => 'Before Construction/Renovations',
        '7' => 'After Construction/Renovations',
        '8' => 'Sold Comps',
        '9' => 'Active Comps',
        '10'=> 'Plat Map'
    ],

    'info_added_by' => [
        'first_dtc'       => 'first_dtc',
        'second_dca'      => 'second_dca',
        'third_dca'       => 'third_dca',
        'wholesale_buyer' => 'wholesale_buyer',
        'final_dca' => 'final_dca',
    ],

    'lien_position' => [
        '1' => 'Superior Lien',
        '2' => 'Inferior Lien',
    ],

    'client_document_type' => [
        '1'  => 'WellsFargo Receipt',
        '2'  => 'WellsFargo Check',
        '3'  => 'Insurance',
        '4'  => 'HUD A to B',
        '5'  => 'HUD B to C',
        '6'  => 'Deed of Trust',
        '7'  => 'Foreclosure Notice',
        '8'  => 'Warranty Deed',
        '9'  => 'Operating Agreement',
        '10' => 'EIN Article',
        '11' => 'LLC Article',
        '12' => 'Legal Fees',
        '13' => 'Others'

    ],

    'master_closing_doc_type' => [
        '1'  => 'Tax Statement',
        '2'  => 'Property Record Card',
        '3'  => 'Clear (Property)',
        '4'  => 'Clear (Owner)',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Trustees Deed',
        '8'  => 'Deed of Trust',
        '9'  => 'Modification',
        '10' => 'Subordination',
        '11' => 'Affidavit',
        '99' => 'Other',

    ],
    'client_renovation_type'  => [
        '1' => 'Bank Deposite',
        '2' => 'Bank Statement',

    ],

    'non_hud_expenditures_sub_cat' =>
        [
            '1'  => 'Loan Payments',
            '2'  => 'Legal Fees',
            '3'  => 'Listing Fee',
            '4'  => 'AA Fee',
            '5'  => 'LLC Fee',
            '6'  => 'Wire Fee',
            '7'  => 'Taxes and Licenses',
            '8'  => 'Travel Expenses',
            '9'  => 'Miscellaneous',
            '10' => 'Drywall',
            '11' => 'Plumbing',
            '12' => 'Painting',
            '13' => 'Electrical',
            '14' => 'Termite',
            '15' => 'HVAC',
            '16' => 'Windows',
            '17' => 'Tile',
            '18' => 'Door',
            '19' => 'Pool Cabinets Finish',
            '20' => 'Appliances',
            '21' => 'Home Accessories',
            '22' => 'Staging/ Inspection',
            '23' => 'Appraisal/ Valuation',
            '24' => 'Dump Fee',
            '25' => 'Dump Fee',
            '26' => 'Floors',
            '27' => 'Ceilings',
            '28' => 'Bathroom',
            '29' => 'Kitchen',
            '30' => 'Roof',
            '31' => 'Jack of All Trades Carpenter',

            '32' => 'Internet',
            '33' => 'Cable',
            '34' => 'Cameras Arlo Pro',
            '35' => 'Water Bills',
            '36' => 'Electric Bills',
            '37' => 'Insurance',
            '38' => 'Interest on Loans',
            '39' => 'Buyer Referral Fee',
            '40' => 'Landscaping',
            '41' => 'property Taxes',
            '42' => '(New Field)',
        ]
    ,

    'non_hud_expenditures_cat' =>
        [
            '1' => 'Utilities',
            '2' => 'Loan',
            '3' => 'Fees',
            '4' => 'Renovation',
            '5' => 'Finish Work',
            '6' => 'Inspection',
            '7' => 'Crawl Space'
        ]
    ,

    'get_a_picture'           =>
        [
            '1'           => '1 Home $75.00',
            '3'           => '3 Homes $175.00',
            '5'           => '5 Homes $275.00',
            'crawl_space' => 'Crawl Space Pictures',
        ],

    'crawl_space_calculation' =>
        [
            '1'  => '75.00',
            '1+' => '50.00',
        ]
    ,
    'first_sort_by'           => [
        "0"                      => "--Select--",
        "owner_name"             => "Owner Name",
        "address"                => "Address",
        "city"                   => "City",
        "zip"                    => "Zip",
        "state"                  => "State",
        "county"                 => "County",
        "sale_price_opening_bid" => "Sales Price/Opening Bid",
        "ppsf"                   => "Price per square foot",
        "sale_date"              => "Sale Date",
        "year_built"              => "Year Built",
        //"sp_number"              => "SP Number#",

        //        "ss_reo_for"             => "SS/REO/Foreclosure",
        //        "comp"                   => "Comp",
        //        "zestimates"             => "Zestimate",
        //        "before_sale_spread"     => "Before Sale Spread",
        //
        //        "1st_lien"               => "1st Lein",
        //        "2nd_lien"               => "2nd Lein",
        //        "3rd_lien"               => "3rd Lein",
        //        "tax_lien"               => "Tax Lein",
        //        "nod"                    => "NOD",
        //        "sold_to"                => "Sold to",
        //        "nos"                    => "NOS",
        //        "before_sale_spread_per" => "Before Sale Spread percent",
        //        "potential_buy"          => "Potential Buy",
        //        "dead_prop"              => "Dead Property",
        //        "est_sale_date"          => "Estimate Sale Date",
        //
        //        "trustee"                => "Trustee",
    ],
    'order_by'                => [
        "asc"  => "Ascending",
        "desc" => "Descending",
    ]
    ,
    'bidding_type'                => [
        "1" =>"To Bid",
        "2" =>"Funds Deposit",
        "3" =>"Funds Withdrawal",
        "4" =>"Redeposit"
    ],

    "aa_account" => [
        "1"=>"La Rochelle",
        "2"=>"Avignon",
        "3"=>"Etienne",
        "4"=>"Marseille"
    ],
    'mortgage_document_type' => [
        '1'  => 'Tax Statement',
        '5'  => 'Deed',
        '6'  => 'Quit Claim Deed',
        '7'  => 'Trustees Deed',
        '8'  => 'Deed of Trust',
        '9'  => 'Modification',
        '10' => 'Subordination',
        '11' => 'Affidavit',
        '12' => 'Order',
        '13' => 'CC&Rs',
        '14' => 'Warranty Deed',
        '15' => 'Satisfaction',
        '16' => 'Tax Lien',
        '17' => 'IRS',
        '18' => "Constable's Deed",
        '19' => "Sheriff's Deed",
        '20' => "Commissioner's Deed",
        '21' => "Appointment",
        '22' => 'Notice',
        '23' => 'HOA Lien Priority',
        '24' => 'HOA/POA Rental Policy',
        '25' => 'Legal Document',
        '99' => 'Other',
    ],
    "states"=> ['AL' => 'Alabama',
                'AK' => 'Alaska',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'DC' => 'District Of Columbia',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'In.diana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PA' => 'Pennsylvania',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming'],

    'tax_code'=>[
      "1"=>'TX §34.21(a) Homestead and Agricultural 2 years',
      "2"=>'TX §34.21(e) Non-Homestead & Non-Agricultural 180 Days',
      "3"=>'TX §209.011 HOA 180 days',
      "4"=>'TX §82.113 Condominium 90 days',
      "5"=>'SC §12-51-95 12 months',
      "6"=>'GA § 48-4-42 12 months'
    ],

    'hide_proprty_detail'=>[
      "2"=>[ //property type
        "21" => "Vacant",
        "22" => "Vacant Undeveloped",
        "25" => "Subdivision and Lot Wholesaling",
        "26" => "Site Location and Assembling Parcels",
        "27" => "Waterfront",
      ],
      "3" =>[
          "38" => "Vacant Land",
      ]
    ],


    'report_type_state' => [
            "MECK8" => "NC", "MECK1" => "NC", "1W6" => "NC", "2W6" => "NC", "3W5" => "NC", "4W7" => "NC", "NCE5" => "NC"
        , "ECM6" => "NC", "FGD3" => "NC", "IRE5" => "NC", "MontC7" => "NC", "NE8" => "NC", "NEC5" => "NC", "NEC7" => "NC"
        , "OE6" => "NC", "SE7" => "NC", "SEC5" => "NC", "WD2" => "NC",
            "1SOUTH5" => "SC",
            "2SOUTH4" => "SC",
            "3SOUTH7" => "SC",
            "C5" => "SC",
            "N7" => "SC",
            "NE5" => "SC",
            "W6" => "SC",
            "W7" => "SC",
            "HAR8"=>"TX",

    ],
    'report_type'=> [
        "NC" => array(
            "MECK8" => ['Anson', 'Cabarrus', 'Catawba', 'Gaston', 'Lincoln', 'Rowan', 'Stanly', 'Union'],
            "MECK1" => ['MECKLENBURG'],
            "1W6" => ['Jackson', 'Swain', 'Macon', 'Graham', 'Clay', 'Cherokee'],
            "2W6" => ['Buncombe', 'Yancey', 'Madison', 'Haywood', 'Henderson', 'Transylvania'],
            "3W5" => ['Cleveland', 'Rutherford', 'Polk', 'McDowell', 'Burke'],
            "4W7" => ['Alleghany', 'Ashe', 'Watauga', 'Wilkes', 'Avery', 'Caldwell', 'Alexander'],
            "NCE5" => ['Dare', 'Tyrrell', 'Washington', 'Hyde', 'Beaufort'],
            "ECM6" => ['Pitt', 'Martin', 'Edgecombe', 'Wilson', 'Wayne', 'Greene'],
            "FGD3" => ['Forsyth', 'Guilford', 'Davidson'],
            "IRE5" => ['Iredell', 'Davie', 'Yadkin', 'Surry', 'Stokes'],
            "MontC7" => ['Montgomery', 'Moore', 'Richmond', 'Randolph', 'Chatham', 'Scotland', 'Lee'],
            "NE8" => ['Currituck', 'Camden', 'Pasquotank', 'Perquimans', 'Gates', 'Bertie', 'Hertford', 'Chowan'],
            "NEC5" => ['Rockingham', 'Caswell', 'Alamance', 'Orange', 'Person'],
            "NEC7" => ['Granville', 'Vance', 'Warren', 'Halifax', 'Northampton', 'Franklin', 'Nash'],
            "OE6" => ['Onslow', 'Carteret', 'Pamlico', 'Jones', 'Craven', 'Lenoir'],
            "SE7" => ['Brunswick', 'New Hanover', 'Pender', 'Duplin', 'Sampson', 'Bladen', 'Columbus'],
            "SEC5" => ['Cumberland', 'Robeson', 'Hoke', 'Harnett', 'Johnston'],
            "WD2" => ['Wake', 'Durham'],
        ),
        "SC" =>  array(

            "1SOUTH5" => ['Horry', 'Marion', 'Florence', 'Williamsburg', 'Georgetown'],
            "2SOUTH4" => ['Berkeley', 'Dorchester', 'Charleston', 'Orangeburg'],
            "3SOUTH7" => ['Beaufort', 'Jasper', 'Hampton', 'Allendale', 'Barnwell', 'Bamberg', 'Colleton'],
            "C5" => ['Richland', 'Lee', 'Sumter', 'Clarendon', 'Calhoun'],
            "N7" => ['York', 'Cherokee', 'Union', 'Spartanburg', 'Chester', 'Fairfield'],
            "NE5" => ['Chesterfield', 'Marlboro', 'Darlington', 'Kershaw', 'Dillon'],
            "W6" => ['Greenville', 'Oconee', 'Pickens', 'Anderson', 'Laurens', 'Abbeville'],
            "W7" => ['Lexington', 'Greenwood', 'Saluda', 'McCormick', 'Edgefield', 'Aiken', 'Newberry'],

        ),
        "TX" => array(
            "HAR8" => ['Harris', 'Fort Bend', 'Galveston', 'Brazoria', 'Liberty', 'Waller', 'Chambers', 'Montgomery'],
        ),
    ],

    'mls_type' => [
        "1" =>"CMLS",
        "2" =>"TMLS",
        "3" =>"TIRAD",
        "4" =>"WRAR",
        "5" =>"FLEX",
        "6" =>"PARAGON",
        "7" =>"NAVICA",

    ],

    'aa_report_sale_type'=>[2,3,4,5,6],

    'strategy_option'=>[
        "1" =>["CIS",false],
        "2" =>["Walk Away",false],
        "3" =>["Buy Back",false],
        "4" =>["HOA",false],
        "5" =>["List & Flip",false],
        "6" =>["Excess Funds",false],
        "7" =>["Others",false],
    ],
    'checklist_option'=>[
        "1" =>["THIRD PARTY AUTHORIZATION",false],
        "2" =>["REAL PROPERTY POWER OF ATTORNEY",false],
        "3" =>["WARRANTY DEED",false],
        "4" =>["ASSIGNMENT OF RIGHT OF RENTS",false],
        "5" =>["ASSIGNMENT OF INSURANCE PROCEEDS",false],
        "6" =>["CONVEYANCE AGREEMENT",false],
        "7" =>["DISCLOSURE & CONSENT",false]
    ],
    "subto_after_foreclosure"=>[
        "1" =>["MASTER DEED, FOLLOW THE FORMAT FOR EACH COUNTY",false],
        "2" =>["RULE TO SHOW CAUSE WRIT OF ASSISTANCE (EVICTION)",false],
    ],
    'subto_document'=>[
        "1" =>"THIRD PARTY AUTHORIZATION",
        "2" =>"REAL PROPERTY POWER OF ATTORNEY",
        "3" =>"WARRANTY DEED",
        "4" =>"ASSIGNMENT OF RIGHT OF RENTS",
        "5" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "6" =>"CONVEYANCE AGREEMENT",
        "7" =>"DISCLOSURE & CONSENT",
    ],
    
    "buy_back_strategy_document"=>[
        "1" =>"AFFIDAVIT",
        "2" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "3" =>"ASSIGNMENT OF NOTE & DT",
        "4" =>"ASSIGNMENT OF RIGHT TO SURPLUS FUNDS",
        "5" =>"ASSIGNMENT CLAIM TO SURPLUS FUNDS",
        "6" =>"DISCLOSURE & CONSENT",
        "7" =>"CONTRACT SALE",
        "8" =>"WARRANTY DEED",
        "9" =>"REAL PROPERTY POWER OF ATTORNEY",
        "10" =>"THIRD PARTY AUTHORIZATION, if applicable",
    ],
    "cis_strategy_document"=>[
        "1" =>"REAL PROPERTY POWER OF ATTORNEY",
        "2" =>"ASSIGNMENT OF RIGHT TO RETAIN COUNSEL AND PURSUE LITIGATION",
        "3" =>"ASSIGNMENT OF INSURANCE",
        "4" =>"ASSIGNMENT OF RIGHT OF SURPLUS FUNDS",
        "5" =>"CONSULTING AGREEMENT",
        "6" =>"DISCLOSURE AGREEMENT",
        "7" =>"THIRD PARTY AUTHORIZATION, if applicable",
    ],
    "walk_away_strategy_document"=>[
        "1" =>"REAL PROPERTY POWER OF ATTORNEY",
        "2" =>"THIRD PARTY AUTHORIZATION",
        "3" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "4" =>"ASSIGNMENT OF RENTS",
        "5" =>"CONVEYANCE AGREEMENT",
        "6" =>"MASTER DEED",
        "7" =>"DISCLOSURE AGREEMENT",
    ],
    
    "tx_subto_document"=>[
        "1" =>"THIRD PARTY AUTHORIZATION",
        "2" =>"REAL PROPERTY POWER OF ATTORNEY",
        "3" =>"WARRANTY DEED",
        "4" =>"DISCLOSURE & CONSENT",
        "5" =>"AGREEMENT FOR REDEMPTION & EXCESS FUNDS PROCEEDS",
        "6" =>"ASSIGNMENT RIGHT OF INSURANCE PROCEEDS",
        "7" =>"ASSIGNMENT OF RIGHT OF RENTS",
    ],
    "subto_document_list"=>[
        "1" =>"THIRD PARTY AUTHORIZATION",
        "2" =>"REAL PROPERTY POWER OF ATTORNEY",
        "3" =>"WARRANTY DEED",
        "4" =>"ASSIGNMENT OF RIGHT OF RENTS",
        "5" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "6" =>"CONVEYANCE AGREEMENT",
        "7" =>"DISCLOSURE & CONSENT",
        "8" =>"AGREEMENT FOR REDEMPTION & EXCESS FUNDS PROCEEDS",
        "9" =>"MASTER DEED",
        "10" =>"CONTRACT SALE",
        "11" =>"AFFIDAVIT",
        "12" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "13" =>"ASSIGNMENT OF NOTE & DT",
        "14" =>"ASSIGNMENT OF RIGHT TO SURPLUS FUNDS",
        "15" =>"ASSIGNMENT CLAIM TO SURPLUS FUNDS",
        "16" =>"TITLE SEARCH",
        "17" =>"TRUSTEES DEED",
    ],

    "all_state_subto_document_list"=>[
        "1" =>"AFFIDAVIT",
        "2" =>"AGREEMENT FOR REDEMPTION & EXCESS FUNDS PROCEEDS",
        "3" =>"ASSIGNMENT CLAIM TO SURPLUS FUNDS",
        "4" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "5" =>"ASSIGNMENT OF INSURANCE PROCEEDS",
        "6" =>"ASSIGNMENT OF NOTE & DT",
        "7" =>"ASSIGNMENT OF RIGHT OF RENTS",
        "8" =>"ASSIGNMENT OF RIGHT TO SURPLUS FUNDS",
        "9" =>"CONTRACT SALE",
        "10" =>"CONVEYANCE AGREEMENT",
        "11" =>"DISCLOSURE & CONSENT",
        "12" =>"MASTER DEED",
        "13" =>"REAL PROPERTY POWER OF ATTORNEY",
        "14" =>"RULE TO SHOW CAUSE",
        "15" =>"THIRD PARTY AUTHORIZATION",
        "16" =>"TITLE REPORT",
        "17" =>"TRUSTEES DEED",
        "18" =>"WARRANTY DEED",
        "19" =>"WRIT OF ASSISTANCE",
        "20" =>"OTHERS",
    ],

    'vehicle_make'=>[
        1=>'Acura',
        2=>'Alfa Romeo',
        3=>'Aston Martin',
        4=>'Audi',
        5=>'Bentley',
        6=>'BMW',
        7=>'Buick',
        8=>'Cadillac',
        9=>'Chevrolet',
        10=>'Chrysler',
        11=>'Dodge',
        12=>'Ferrari',
        13=>'FIAT',
        14=>'Ford',
        15=>'Genesis',
        16=>'GMC',
        17=>'Honda',
        18=>'Hyundai',
        19=>'INFINITI',
        20=>'Jaguar',
        21=>'Jeep',
        22=>'Kia',
        23=>'Lamborghini',
        24=>'Land Rover',
        25=>'Lexus',
        26=>'Lincoln',
        27=>'Lotus',
        28=>'Maserati',
        29=>'Mazda',
        30=>'McLaren',
        31=>'Mercedes-Benz',
        32=>'MINI',
        33=>'Mitsubishi',
        34=>'Nissan',
        35=>'Porsche',
        36=>'RAM',
        37=>'Rolls-Royce',
        38=>'Scion',
        39=>'smart',
        40=>'Subaru',
        41=>'Tesla',
        42=>'Toyota',
        43=>'Volkswagen',
        44=>'Volvo',
    ],
    'vehicle_sale_type'=>[
        1=>'Vehicle Sale'
    ],

    'social_media_type'=>[
        ["id"=>1,"text"=>"Facebook","icon"=>"fa-facebook-f"],
        ["id"=>2,"text"=>"YouTube","icon"=>"fa-youtube"],
        ["id"=>3,"text"=>"WhatsApp","icon"=>"fa-whatsapp"],
        ["id"=>4,"text"=>"Instagram","icon"=>"fa-instagram"],
        ["id"=>5,"text"=>"TikTok","icon"=>"fa-tiktok"],
        ["id"=>6,"text"=>"WeChat","icon"=>"fa-webchat"],
        ["id"=>7,"text"=>"Messenger","icon"=>"fa-messanger"],
        ["id"=>8,"text"=>"Telegram","icon"=>"fa-telegram"],
        ["id"=>9,"text"=>"Viber","icon"=>"fa-viber"],
        ["id"=>10,"text"=>"Snapchat","icon"=>"fa-snapchat"],
        ["id"=>11,"text"=>"Douyin","icon"=>"fa-douyin"],
        ["id"=>12,"text"=>"Baidu","icon"=>"fa-baidu"],
        ["id"=>13,"text"=>"Qzone","icon"=>"fa-qzone"],
        ["id"=>14,"text"=>"Spotify","icon"=>"fa-spotify"],
        ["id"=>15,"text"=>"X (Twitter)","icon"=>"fa-twitter"],
        ["id"=>16,"text"=>"Sina Weibo","icon"=>"fa-sina-weibo"],
        ["id"=>17,"text"=>"Pinterest","icon"=>"fa-pinterest"],
        ["id"=>18,"text"=>"Reddit","icon"=>"fa-reddit"],
        ["id"=>19,"text"=>"Kuaishou","icon"=>"fa-kuaishou"],
        ["id"=>20,"text"=>"Bilibili","icon"=>"fa-bilibili"],
        ["id"=>21,"text"=>"Microsoft Teams","icon"=>"fa-microsoft"],
        ["id"=>22,"text"=>"LinkedIn","icon"=>"fa-linkedin"],
        ["id"=>23,"text"=>"Quora","icon"=>"fa-quora"],
        ["id"=>24,"text"=>"Vimeo","icon"=>"fa-vimeo"],
        ["id"=>25,"text"=>"Line","icon"=>"fa-line"],
        ["id"=>26,"text"=>"Xiaohongshu","icon"=>"fa-xiaohongshu"],
        ["id"=>27,"text"=>"Discord","icon"=>"fa-discord"],
        ["id"=>28,"text"=>"ShareChat","icon"=>"fa-shrechat"],
        ["id"=>29,"text"=>"Threads","icon"=>"fa-threads"],
        ["id"=>30,"text"=>"Josh","icon"=>"fa-josh"],
        ["id"=>31,"text"=>"Twitch","icon"=>"fa-twitch"],
        ["id"=>32,"text"=>"Tumblr","icon"=>"fa-tumblr"],
        ["id"=>33,"text"=>"Medium","icon"=>"fa-medium"],
        ["id"=>34,"text"=>"VK (Vkontakte)","icon"=>"fa-vkontakte"],
        ["id"=>35,"text"=>"Rumble","icon"=>"fa-rumble"],
        ["id"=>36,"text"=>"Other","icon"=>"fa-user-circle"]
    ]
  

    
];
