export const formConstants = {

    // COUNTRIES
    countries: [
        "Alamance",
        "Alexander",
        "Alleghany",
        "Anson",
        "Ashe",
        "Avery",
        "Beaufort",
        "Bertie",
        "Bladen",
        "Brunswick",
        "Buncombe",
        "Burke",
        "Cabarrus",
        "Caldwell",
        "Camden",
        "Carteret",
        "Caswell",
        "Catawba",
        "Chatham",
        "Cherokee",
        "Chowan",
        "Clay",
        "Cleveland",
        "Craven",
        "Cumberland",
        "Currituck",
        "Dare",
        "Davidson",
        "Davie",
        "Duplin",
        "Durham",
        "Edgecombe",
        "Forsyth",
        "Franklin",
        "Gaston",
        "Gates",
        "Graham",
        "Granville",
        "Greene",
        "Guilford",
        "Halifax",
        "Harnett",
        "Haywood",
        "Henderson",
        "Hertford",
        "Hoke",
        "Hyde",
        "Iredell",
        "Jackson",
        "Johnston",
        "Jones",
        "Lee",
        "Lenoir",
        "Lincoln",
        "McDowell",
        "Macon",
        "Madison",
        "Martin",
        "Mecklenburg",
        "Mitchell",
        "Montgomery",
        "Tyrrell",
        "Union",
        "Vance",
        "Wake",
        "Warren",
        "Washington",
        "Watauga",
        "Wayne",
        "Wilkes",
        "Wilson",
        "Yadkin",
        "Yancey"

     ],

     // STATES 

     states: {
           'AL' :'Alabama',
            'AK' :'Alaska',
            'AZ':'Arizona',
            'AR' : 'Arkansas',
            'CA' : 'California',
            'CO'  :'Colorado',
            'CT'  :'Connecticut',
            'DE'  :'Delaware',
            'DC'  :'District Of Columbia',
            'FL'  :'Florida',
            'GA'  :'Georgia',
            'HI'  :'Hawaii',
            'ID'  :'Idaho',
            'IL'  :'Illinois',
            'IN'  :'Indiana',
            'IA'  :'Iowa',
            'KS'  :'Kansas',
            'KY'  :'Kentucky',
            'LA'  :'Louisiana',
            'ME'  :'Maine',
            'MD'  :'Maryland',
            'MA'  :'Massachusetts',
            'MI'  :'Michigan',
            'MN'  :'Minnesota',
            'MS'  :'Mississippi',
            'MO'  :'Missouri',
            'MT'  :'Montana',
            'NE'  :'Nebraska',
            'NV'  :'Nevada',
            'NH'  :'New Hampshire',
            'NJ'  :'New Jersey',
            'NM'  :'New Mexico',
            'NY'  :'New York',
            'NC' :'North Carolina',
            'ND'  :'North Dakota',
            'OH'  :'Ohio',
            'OK'  :'Oklahoma',
            'OR'  :'Oregon',
            'PA'  :'Pennsylvania',
            'RI'  :'Rhode Island',
            'SC' : 'South Carolina',
            'SD'  :'South Dakota',
            'TN'  :'Tennessee',
            'TX'  :'Texas',
            'UT'  :'Utah',
            'VT'  :'Vermont',
            'VA'  :'Virginia',
            'WA'  :'Washington',
            'WV'  :'West Virginia',
            'WI' : 'Wisconsin',
            'WY'  :'Wyoming',
    },

    // COUNT-10
    counter_10: [1,2,3,4,5,6,7,8,9,10],

    counter_5: [0,1,2,3,4,5],

    counter_float_5: ['0.0','1.0','1.5','2.0','2.5','3.0','3.5','4.0','4.5','5.0'],


    fire_place_option: {
        "0":"N/A",
        "1":"Yes",
        "2":"No"
    }, 
    
    request_type:[
        {"item":"All Properties","value":""},
        // {"item":"Amount In","value":"amount_in"},
       // {"item":"Potential Buys","value":"potential_buy"},
        //{"item":"Bid/Offer On Properties","value":"bid_offer_on_property"},
        //{"item":"Bidding/Offer in Process","value":"bidding_in_process"},
        //{"item":"Bid/Offer Confirmed","value":"bid_offer_confirmed"},
        {"item":"Properties Acquisition A to B","value":"property_purchased_acq_a_to_b"},
        //{"item":"Properties Under Contract/In Escrow","value":"property_in_escrow"},
        //{"item":"Deposit To Be Returned","value":"deposit_to_be_returned"},
        {"item":"Properties Closed B to C","value":"property_closed"},
        {"item":"Properties My Passed On","value":"passit"},
        {"item":"Buy it Request","value":"buyit"}
    ]
};
